version: '3'
services:
  ws:
    build:
      context: ../..
      dockerfile: docker/optimpdf_run/Dockerfile
    image: optimpdf
    user: 1000:1000
    volumes:
      - .:/workspace
    working_dir: /workspace
