version: '3'
services:
  optimpdf:
    build: .
    image: optimpdf:mvn-im7
    user: ${UID}:${GID}
    volumes:
      - ${HOME}/.m2:/myhome/.m2
      - ../../optimpdf:/proj
    working_dir: /proj
    environment:
      - MAVEN_CONFIG=/myhome/.m2
    command: mvn -Duser.home=/myhome test
