version: '3'
services:
  optimpdf_im6:
    build:
      context: .
      dockerfile: Dockerfile.im6
    image: optimpdf:mvn-im6
    user: ${UID}:${GID}
    volumes:
      - ${HOME}/.m2:/myhome/.m2
      - ../../optimpdf:/proj
    working_dir: /proj
    environment:
      - MAVEN_CONFIG=/myhome/.m2
    command: mvn -Duser.home=/myhome test

  optimpdf_im7:
    build:
      context: .
      dockerfile: Dockerfile.im7
    image: optimpdf:mvn-im7
    user: ${UID}:${GID}
    volumes:
      - ${HOME}/.m2:/myhome/.m2
      - ../../optimpdf:/proj
    working_dir: /proj
    environment:
      - MAVEN_CONFIG=/myhome/.m2
    command: mvn -Duser.home=/myhome test
