version: '3'
services:
  optimpdf:
    build: .
    image: optimpdf
    user: ${UID}:${GID}
    volumes:
      - ../target:/mylib
      - .:/work
    working_dir: /work
    command: java -jar /mylib/optimpdf-1.0.0-jar-with-dependencies.jar -d output -u input
