FROM docker.io/library/eclipse-temurin:25-alpine as builder
RUN apk --update-cache add maven imagemagick
WORKDIR /optimpdf
COPY . /optimpdf
RUN mvn package

FROM docker.io/library/eclipse-temurin:25-jre-alpine as runner
COPY --from=builder /optimpdf/target/optimpdf-*-jar-with-dependencies.jar /optimpdf.jar
ENTRYPOINT ["java", "-jar", "/optimpdf.jar"]
